Fix formatting of relative paths
Prior to vulture 2.2, it was possible to pass an absolute path below the current directory, and the report showed a relative path instead:

With vulture 2.1, inside `~/proj/qutebrowser/git/`:

    $ vulture ~/proj/qutebrowser/git/qutebrowser/qutebrowser.py
    qutebrowser/qutebrowser.py:138: unused function 'directory' (60% confidence)
    qutebrowser/qutebrowser.py:186: unused function 'main' (60% confidence)

With vulture 2.3:

    $ vulture ~/proj/qutebrowser/git/qutebrowser/qutebrowser.py
    /home/florian/proj/qutebrowser/git/qutebrowser/qutebrowser.py:138: unused function 'directory' (60% confidence)
    /home/florian/proj/qutebrowser/git/qutebrowser/qutebrowser.py:186: unused function 'main' (60% confidence)

This is due to #226, notably the `path.relative_to(os.curdir)` in `utils.format_path` - this won't work properly if the input is absolute:

    >>> import os, pathlib
    >>> os.getcwd()
    '/tmp'
    >>> pathlib.Path('/tmp/somefile').relative_to('.')
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/lib/python3.9/pathlib.py", line 928, in relative_to
        raise ValueError("{!r} is not in the subpath of {!r}"
    ValueError: '/tmp/somefile' is not in the subpath of '' OR one path is relative and the other is absolute.
    >>> pathlib.Path('/tmp/somefile').relative_to(pathlib.Path.cwd())
    PosixPath('somefile')